spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/IDMProjectDB
    # url: jdbc:postgresql://postgres:5432/IDMProjectDB
    username: postgres
    password: Password1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
